### ISSUE TITLE
Integrate checkstyle

### ISSUE THREAD

**Issue by carltonwhitehead** [carltonwhitehead/coner#2]

**Comment by jshort** [comment]
So this brings into the conversation warning vs error.  Errors fail the build and we have control over which is which.  Right now we have a lot of javadoc check failures and I'm inclined to make them errors since I feel we need good documentation and since it is green field development, it doesn't hurt to start off on the right foot.

**Comment by carltonwhitehead** [comment]
I agree we should have good javadocs. I'm happy to flag those as failures

**Comment by jshort** [comment]
Unfortunately there is no way to suppress the 'errors' thrown with lambdas and hence we can never get the build to not fail until checkstyle comes out with a java 8 release.  I'd say it is not enough of an issue to just advise to run checkstyle before a PR.

However, I can play with travis to see if I can run some grep commands to make sure that if there are errors, that if they are only lambda errors, then pass the build, otherwise fail.  I will create a separate issue to track that.

**Comment by carltonwhitehead** [comment]
Are you sure? https://github.com/checkstyle/checkstyle/issues/10

**Comment by carltonwhitehead** [comment]
It sounds like the current version has the issue. I wonder if one of the releases since it was introduced 3 months ago doesn't have the regression

**Comment by jshort** [comment]
Ok I figured it out (mvn is coming back to me).  So the maven-checkstyle-plugin version 2.13 uses checkstyle 5.7.  The latter does not work with java 8 lambdas.  But I can override the default dependency in our parent pom to use checkstyle 5.9.  Hell, I should just go ahead and use 6.2 if it works because then I don't have to include the NeedBraces62Check anymore.

I'll give this all a try and update the PR.
